### ISSUE TITLE
Function prefixing

### ISSUE THREAD

**Issue by bpbond** [Microbial-Explicit-Model/MEMC#32]
Three of the MEMC functions start with "memc_" prefixes: `memc_modfit`, `memc_sensfunc`, and `memc_sensrange`.

@kdorheim I'm wondering if you have any thoughts about making this a common prefix across *all* the user-facing package functions. Some people are in favor of this -- see e.g. https://forum.posit.co/t/function-naming-conventions-and-best-practice/3381 -- but others find it unwieldy. 

Personally, I like the idea and find it helpful (e.g. when using auto-complete) but don't have strong feelings. And this is YOUR package. Anyway, just wanted to check.

**Comment by kdorheim** [comment]
That is a good question and something that I have been wrestling with for a bit now (see #12)I don't feel that strongly about, but I do think it is needed for the functions you highlighted above since modfit, sensefunc, and sensrange are all exported by the FME package. I'd appreciate some external input on this because I keep on going back and forth on it and now seems like the time to do the rename the if we choose to do so.

**Comment by bpbond** [comment]
> it is needed for the functions you highlighted above since modfit, sensefunc, and sensrange are all exported by the FME package

Ah! Got it. I was wondering.

Personally, I like the `memc_solve` and `memc_configure` etc. approach, but that's just my vote.

**Comment by kdorheim** [comment]
👍 I am going to implement it then!
